#!/usr/bin/env bash
#
# Onion Service Setup Script for Anarchy Node
#
# This script:
# 1. Generates torrc configuration for Onion Service
# 2. Sets up the hidden service directory
# 3. Extracts the .onion address after Tor starts
# 4. Outputs the --public-addr command for the node
#
# Usage:
#   sudo ./onion-service.sh setup      # Generate torrc (uses ~/.tor/ for permissions)
#   ./onion-service.sh address         # Get .onion address (no sudo needed)
#   ./onion-service.sh public          # Generate --public-addr
#   ./onion-service.sh status          # Check service status
#
set -euo pipefail

# Configuration - prefer user directory for permission compatibility
USER_TOR_DIR="${HOME}/.tor/anarchy-node"
SYSTEM_TOR_DIR="/var/lib/tor/anarchy-node"
TOR_CONFIG_DIR="${TOR_CONFIG_DIR:-/etc/tor}"
TORRC_SNIPPET="${TOR_CONFIG_DIR}/torrc.d/anarchy.conf"
ONION_PORT="${ONION_PORT:-30333}"
LOCAL_PORT="${LOCAL_PORT:-30333}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

# Find the hostname file (check system dir first, then user dir)
find_hostname_file() {
    if [[ -f "${SYSTEM_TOR_DIR}/hostname" ]]; then
        echo "${SYSTEM_TOR_DIR}/hostname"
    elif [[ -f "${USER_TOR_DIR}/hostname" ]]; then
        echo "${USER_TOR_DIR}/hostname"
    else
        echo ""
    fi
}

# Check if running as root (required for torrc editing)
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root for setup"
        log_info "Try: sudo $0 $*"
        exit 1
    fi
}

# Validate .onion address format (56 characters base32 + .onion)
validate_onion_address() {
    local addr="$1"
    # v3 Onion addresses are 56 characters of base32 + .onion
    if [[ ! "$addr" =~ ^[a-z2-7]{56}\.onion$ ]]; then
        return 1
    fi
    return 0
}

# Generate torrc configuration snippet (uses system Tor directory with debian-tor ownership)
generate_torrc() {
    check_root
    
    log_info "Generating Onion Service configuration..."
    
    # Use system Tor directory (required for debian-tor user)
    local tor_data_dir="${SYSTEM_TOR_DIR}"
    
    # Create torrc.d directory if it doesn't exist
    mkdir -p "${TOR_CONFIG_DIR}/torrc.d"
    
    # Create Tor data directory with proper permissions for debian-tor
    mkdir -p "${tor_data_dir}"
    
    # Set ownership to debian-tor (the user Tor runs as on Debian/Ubuntu)
    if chown debian-tor:debian-tor "${tor_data_dir}" 2>/dev/null; then
        log_info "Set ownership to debian-tor"
    elif chown _tor:_tor "${tor_data_dir}" 2>/dev/null; then
        log_info "Set ownership to _tor (macOS)"
    elif chown tor:tor "${tor_data_dir}" 2>/dev/null; then
        log_info "Set ownership to tor"
    else
        log_warn "Could not set ownership - Tor may fail to start"
    fi
    chmod 700 "${tor_data_dir}"
    
    log_info "Created Tor data directory: ${tor_data_dir}"
    
    # Generate torrc snippet
    cat > "${TORRC_SNIPPET}" << EOF
# Anarchy Node Onion Service Configuration
# Generated by onion-service.sh on $(date -Iseconds)

# Hidden Service for Anarchy node P2P
HiddenServiceDir ${tor_data_dir}
HiddenServicePort ${ONION_PORT} 127.0.0.1:${LOCAL_PORT}

# Security settings
HiddenServiceVersion 3
EOF

    log_info "Created torrc configuration: ${TORRC_SNIPPET}"
    
    # Check if main torrc includes the snippet directory
    if grep -q "^%include.*torrc.d" "${TOR_CONFIG_DIR}/torrc" 2>/dev/null; then
        log_info "Main torrc already includes torrc.d directory"
    else
        log_warn "Main torrc may not include torrc.d directory"
        log_info "Adding include directive to ${TOR_CONFIG_DIR}/torrc..."
        echo "%include ${TOR_CONFIG_DIR}/torrc.d/*.conf" >> "${TOR_CONFIG_DIR}/torrc"
        log_info "Added: %include ${TOR_CONFIG_DIR}/torrc.d/*.conf"
    fi
    
    log_info "Configuration complete. Restart Tor to activate:"
    echo "  sudo systemctl restart tor@default"
    echo ""
    log_info "After Tor restarts (wait a few seconds), get your .onion address with:"
    echo "  sudo $0 address"
}

# Get the .onion address (sudo required to read from system directory)
get_onion_address() {
    local hostname_file
    hostname_file=$(find_hostname_file)
    
    if [[ -z "$hostname_file" ]]; then
        log_error "Hostname file not found"
        log_info "Checked: ${USER_TOR_DIR}/hostname"
        log_info "Checked: ${SYSTEM_TOR_DIR}/hostname"
        log_info "Make sure Tor is running and has created the hidden service"
        log_info "Try: sudo systemctl status tor"
        exit 1
    fi
    
    local onion_addr
    onion_addr=$(cat "$hostname_file")
    
    if ! validate_onion_address "$onion_addr"; then
        log_error "Invalid .onion address format: ${onion_addr}"
        exit 1
    fi
    
    echo "$onion_addr"
}

# Generate --public-addr command for the node (no sudo required)
generate_public_addr() {
    local onion_addr
    onion_addr=$(get_onion_address)
    
    # Remove .onion suffix for multiaddr format
    local onion_base="${onion_addr%.onion}"
    
    log_info "Your Onion Service address: ${onion_addr}"
    log_info ""
    log_info "Use this --public-addr flag when starting your node:"
    echo ""
    echo "  --public-addr /onion3/${onion_base}:${ONION_PORT}"
    echo ""
    log_info "Full command example:"
    echo ""
    echo "  ./scripts/anarchy-tor.sh ./target/release/anarchy-node \\"
    echo "    --tor-mode=forced \\"
    echo "    --public-addr /onion3/${onion_base}:${ONION_PORT} \\"
    echo "    --chain local \\"
    echo "    --name \"MyAnarchyNode\""
    echo ""
}

# Check service status
check_status() {
    log_info "Checking Tor service status..."
    
    # Check if Tor is running
    if systemctl is-active --quiet tor 2>/dev/null; then
        log_info "Tor service: ${GREEN}running${NC}"
    elif pgrep -x tor > /dev/null; then
        log_info "Tor process: ${GREEN}running${NC} (not via systemd)"
    else
        log_error "Tor is not running"
        log_info "Start with: sudo systemctl start tor"
        return 1
    fi
    
    # Check config file
    if [[ -f "${TORRC_SNIPPET}" ]]; then
        log_info "Config file: ${GREEN}exists${NC} (${TORRC_SNIPPET})"
    else
        log_warn "Config file: ${YELLOW}not found${NC}"
        log_info "Run: sudo $0 setup"
        return 1
    fi
    
    # Check hostname file
    local hostname_file
    hostname_file=$(find_hostname_file)
    
    if [[ -n "$hostname_file" && -f "$hostname_file" ]]; then
        log_info "Onion address: ${GREEN}available${NC}"
        echo ""
        log_info "Address: $(cat "$hostname_file")"
        log_info "Location: ${hostname_file}"
    else
        log_warn "Onion address: ${YELLOW}not yet generated${NC}"
        log_info "Wait for Tor to generate the address (may take a few seconds)"
        log_info "Expected locations:"
        log_info "  - ${USER_TOR_DIR}/hostname"
        log_info "  - ${SYSTEM_TOR_DIR}/hostname"
    fi
    
    return 0
}

# Stop Tor service
stop_tor() {
    log_info "Stopping Tor service..."
    
    if systemctl is-active --quiet tor 2>/dev/null; then
        sudo systemctl stop tor
        log_info "Tor service stopped"
    else
        log_warn "Tor service was not running"
    fi
}

# Print usage
usage() {
    cat << EOF
Onion Service Setup Script for Anarchy Node

Usage: $0 <command>

Commands:
  setup     Generate torrc configuration (requires sudo)
  address   Get the .onion address (no sudo needed)
  public    Generate the --public-addr multiaddr (no sudo needed)
  status    Check Onion Service status
  stop      Stop Tor service (requires sudo)
  help      Show this help message

Data Directories:
  User directory (preferred): ~/.tor/anarchy-node/
  System directory (fallback): /var/lib/tor/anarchy-node/

Environment Variables:
  TOR_CONFIG_DIR  Tor configuration directory (default: /etc/tor)
  ONION_PORT      External port for the Onion Service (default: 30333)
  LOCAL_PORT      Local port the node listens on (default: 30333)

Examples:
  # Initial setup (requires sudo)
  sudo $0 setup
  sudo systemctl restart tor
  
  # Wait a few seconds, then get .onion address (no sudo)
  sleep 3
  $0 address
  
  # Get full --public-addr command (no sudo)
  $0 public
  
  # Check status
  $0 status

EOF
}

# Main entry point
main() {
    local cmd="${1:-help}"
    
    case "$cmd" in
        setup)
            generate_torrc
            ;;
        address)
            get_onion_address
            ;;
        public)
            generate_public_addr
            ;;
        status)
            check_status
            ;;
        stop)
            stop_tor
            ;;
        help|--help|-h)
            usage
            ;;
        *)
            log_error "Unknown command: $cmd"
            usage
            exit 1
            ;;
    esac
}

main "$@"
